export const trendingWebsites = [
  { name: "Google", url: "https://www.google.com" },
  { name: "YouTube", url: "https://www.youtube.com" },
  { name: "Instagram", url: "https://www.instagram.com" },
  { name: "WhatsApp", url: "https://www.whatsapp.com" },
  { name: "ChatGPT", url: "https://chatgpt.com" },
  { name: "Amazon India", url: "https://www.amazon.in" },
  { name: "Wikipedia", url: "https://www.wikipedia.org" },
  { name: "X (Twitter)", url: "https://www.x.com" },
  { name: "Reddit", url: "https://www.reddit.com" },
  { name: "Quora", url: "https://www.quora.com" },
  { name: "LinkedIn", url: "https://www.linkedin.com" },
  { name: "OpenAI", url: "https://www.openai.com" },
  { name: "Netflix", url: "https://www.netflix.com" },
  { name: "Samsung", url: "https://www.samsung.com" },
  { name: "Adobe", url: "https://www.adobe.com" },
  { name: "Pinterest", url: "https://www.pinterest.com" },
  { name: "Telegram", url: "https://t.me" },
];
